### ISSUE TITLE
Segfault from zo fuzzer

### ISSUE THREAD

**Issue by samth** [racket/racket#1070]
This consistently segfaults (on linux):

```
$ racket  -l tests/racket/stress/fuzz --   -s 817020884 -f racket/collects/syntax/compiled/free-vars_rkt.zo
```

**Comment by samth** [comment]
Here's a stack trace:

```
(gdb) where
#0  0x00007ffff711bcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff711f0d8 in __GI_abort () at abort.c:89
#2  0x00000000006b4b4e in fault_handler (sn=<optimized out>, si=0xa1fa30, ctx=<optimized out>) at ../../../racket/gc2/sighand.c:99
#3  <signal handler called>
#4  0x0000000000670632 in unmarshal_free_id_info (ut=0x7ffff63084e8, p=0x6) at ../../../racket/gc2/../src/syntax.c:6808
#5  scope_unmarshal_content (box=0x7ffff630ae98, ut=0x7ffff63084e8) at ../../../racket/gc2/../src/syntax.c:6899
#6  0x0000000000670930 in list_to_scope_set (l=0x7ffff630afc8, ut=0x7ffff63084e8) at ../../../racket/gc2/../src/syntax.c:6553
#7  0x000000000066ff4e in datum_to_wraps (w=0x7ffff630af98, ut=0x7ffff63084e8) at ../../../racket/gc2/../src/syntax.c:6713
#8  0x000000000067131e in datum_to_syntax_inner (o=0x7ffff5de3268, ut=0x7ffff63084e8, stx_src=0x99aa80 <scheme_false>, stx_wraps=0x99aa80 <scheme_false>, ht=0x0, tainted=tainted@entry=0)
    at ../../../racket/gc2/../src/syntax.c:7210
#9  0x0000000000671b0e in general_datum_to_syntax (o=0x7ffff630afe8, ut=0x7ffff63084e8, stx_src=0x99aa80 <scheme_false>, stx_wraps=0x99aa80 <scheme_false>, can_graph=can_graph@entry=0, 
    copy_props=copy_props@entry=0) at ../../../racket/gc2/../src/syntax.c:7286
#10 0x00000000006752f3 in scheme_unmarshal_datum_to_syntax (o=<optimized out>, ut=<optimized out>, can_graph=can_graph@entry=0) at ../../../racket/gc2/../src/syntax.c:7334
#11 0x00000000006130bf in read_compact (port=0x7ffff63052f8, use_stack=use_stack@entry=0) at ../../../racket/gc2/../src/read.c:4821
#12 0x000000000060abd1 in read_compiled (params=0x7fffffffabc0, ht=0x7ffff63037e8, pos=1, col=-1, line=<optimized out>, stxsrc=0x0, port=0x7ffff6303620) at ../../../racket/gc2/../src/read.c:5661
#13 read_inner_inner (port=0x7ffff6303620, stxsrc=0x0, ht=0x7ffff63037e8, indentation=0x99c438 <scheme_null>, params=params@entry=0x7fffffffabc0, comment_mode=comment_mode@entry=2, pre_char=<optimized out>, 
    pre_char@entry=-1, table=0x0, get_info=get_info@entry=0) at ../../../racket/gc2/../src/read.c:1438
#14 0x000000000060ed1e in _internal_read (port=0x7ffff6303620, stxsrc=0x0, crc=<optimized out>, cant_fail=cant_fail@entry=0, recur=0, expose_comment=0, extra_char=-1, init_readtable=0x0, magic_sym=0x0, 
    magic_val=0x0, delay_load_info=0x99aa80 <scheme_false>, get_info=get_info@entry=0) at ../../../racket/gc2/../src/read.c:2353
#15 0x000000000060f440 in scheme_internal_read_k () at ../../../racket/gc2/../src/read.c:2427
#16 0x0000000000488d45 in scheme_top_level_do_worker (k=k@entry=0x60f380 <scheme_internal_read_k>, eb=eb@entry=0, new_thread=new_thread@entry=0, dyn_state=dyn_state@entry=0x0)
    at ../../../racket/gc2/../src/fun.c:1322
#17 0x0000000000489059 in scheme_top_level_do (k=k@entry=0x60f380 <scheme_internal_read_k>, eb=eb@entry=0) at ../../../racket/gc2/../src/fun.c:1210
#18 0x000000000060f258 in scheme_internal_read (port=0x7ffff6303620, stxsrc=stxsrc@entry=0x0, crc=crc@entry=-1, cantfail=cantfail@entry=0, recur=<optimized out>, expose_comment=expose_comment@entry=0, 
    pre_char=pre_char@entry=-1, init_readtable=0x0, magic_sym=magic_sym@entry=0x0, magic_val=magic_val@entry=0x0, delay_load_info=delay_load_info@entry=0x0) at ../../../racket/gc2/../src/read.c:2458
#19 0x00000000005e752a in do_read_f (who=0x704afb "read", argc=<optimized out>, argv=0x7ffff3bf1ed8, recur=0) at ../../../racket/gc2/../src/portfun.c:2934
```
