### ISSUE TITLE
segfault in expander found by continuation tests

### ISSUE THREAD

**Issue by samth** [racket/racket#1247]
Error here in DrDr:

http://drdr.racket-lang.org/34013/racket/share/pkgs/redex-examples/redex/examples/delim-cont/randomized-tests.rkt

Seed: 1743146354 (not necessarily the one that DrDr used).

Stack trace:

```
#11 shift_lifted_reference (tl=0x300000002, tl=0x300000002, tl=0x300000002, tl=0x300000002, tl=0x300000002, info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90, 
    info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90, delta=0) at ../../../racket/gc2/../src/resolve.c:2296
#12 scheme_resolve_expr (expr=0x7f7f9f81e998, info=0x7f7f9e0b4f90) at ../../../racket/gc2/../src/resolve.c:2165
#13 0x0000000000652baa in resolve_branch (o=0x7f7f9ea37f18, o=0x7f7f9ea37f18, o=0x7f7f9ea37f18, o=0x7f7f9ea37f18, o=0x7f7f9ea37f18, info=0x7f7f9e0b4f90, 
    info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90)
    at ../../../racket/gc2/../src/resolve.c:438
#14 scheme_resolve_expr (expr=0x7f7f9ea37f18, info=0x7f7f9e0b4f90) at ../../../racket/gc2/../src/resolve.c:2187
#15 0x0000000000652baa in resolve_branch (o=0x7f7f9ea37f40, o=0x7f7f9ea37f40, o=0x7f7f9ea37f40, o=0x7f7f9ea37f40, o=0x7f7f9ea37f40, info=0x7f7f9e0b4f90, 
    info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90, info=0x7f7f9e0b4f90)
    at ../../../racket/gc2/../src/resolve.c:438
#16 scheme_resolve_expr (expr=0x7f7f9ea37f40, info=0x7f7f9e0b4f90) at ../../../racket/gc2/../src/resolve.c:2187
#17 0x0000000000650110 in scheme_resolve_lets (form=<optimized out>, info=0x7f7f9e0b4e60) at ../../../racket/gc2/../src/resolve.c:1094
#18 0x000000000065423b in scheme_resolve_expr (expr=0x7f7f9ea19718, info=0x7f7f9e0b4e60) at ../../../racket/gc2/../src/resolve.c:2193
#19 0x0000000000652b89 in resolve_branch (o=0x7f7f9ea3f598, o=0x7f7f9ea3f598, o=0x7f7f9ea3f598, o=0x7f7f9ea3f598, o=0x7f7f9ea3f598, info=0x7f7f9e0b4e60, 
    info=0x7f7f9e0b4e60, info=0x7f7f9e0b4e60, info=0x7f7f9e0b4e60, info=0x7f7f9e0b4e60, info=0x7f7f9e0b4e60, info=0x7f7f9e0b4e60)
    at ../../../racket/gc2/../src/resolve.c:437
#20 scheme_resolve_expr (expr=0x7f7f9ea3f598, info=0x7f7f9e0b4e60) at ../../../racket/gc2/../src/resolve.c:2187
#21 0x0000000000650110 in scheme_resolve_lets (form=<optimized out>, info=0x7f7f9e0b4c00) at ../../../racket/gc2/../src/resolve.c:1094
#22 0x000000000065423b in scheme_resolve_expr (expr=0x7f7f9f895a80, info=0x7f7f9e0b4c00) at ../../../racket/gc2/../src/resolve.c:2193
#23 0x0000000000652b89 in resolve_branch (o=0x7f7f9ea46c48, o=0x7f7f9ea46c48, o=0x7f7f9ea46c48, o=0x7f7f9ea46c48, o=0x7f7f9ea46c48, info=0x7f7f9e0b4c00, 
    info=0x7f7f9e0b4c00, info=0x7f7f9e0b4c00, info=0x7f7f9e0b4c00, info=0x7f7f9e0b4c00, info=0x7f7f9e0b4c00, info=0x7f7f9e0b4c00)
    at ../../../racket/gc2/../src/resolve.c:437
#24 scheme_resolve_expr (expr=0x7f7f9ea46c48, info=0x7f7f9e0b4c00) at ../../../racket/gc2/../src/resolve.c:2187
#25 0x0000000000650110 in scheme_resolve_lets (form=<optimized out>, info=0x7f7f9e0b4a08) at ../../../racket/gc2/../src/resolve.c:1094
#26 0x000000000065423b in scheme_resolve_expr (expr=0x7f7f9f8861b0, info=0x7f7f9e0b4a08) at ../../../racket/gc2/../src/resolve.c:2193
#27 0x0000000000651edd in resolve_closure_compilation (_data=<optimized out>, info=0x7f7f9e0b48a0, can_lift=<optimized out>, 
    convert=<error reading variable: Cannot access memory at address 0x0>, just_compute_lift=0, precomputed_lift=0x0)
    at ../../../racket/gc2/../src/resolve.c:1856
#28 0x0000000000654226 in scheme_resolve_expr (expr=0x7f7f9f880c10, info=0x7f7f9e0b48a0) at ../../../racket/gc2/../src/resolve.c:2191
#29 0x00000000006554f3 in resolve_application (o=<optimized out>, orig_info=0x7f7f9e0b4678, already_resolved_arg_count=<optimized out>)
    at ../../../racket/gc2/../src/resolve.c:221
#30 0x0000000000652876 in scheme_resolve_expr (expr=0x7f7f9ea88f38, info=0x7f7f9e0b4678) at ../../../racket/gc2/../src/resolve.c:2177
```

I have the crash recorded under rr, but I don't yet know if I can reproduce it directly on the command line. Running the test repeatedly until crash has consistently reproduced the error, though.

**Comment by samth** [comment]
reproducible with:

```
~/sw/plt/racket/src/build/racket/racket3m  -l  redex/examples/delim-cont/randomized-tests -- --seed 1743146354 --rules 2250 --size 3
```

**Comment by samth** [comment]
Unfortunately the log gets truncated when it crashes, but it's at https://gist.github.com/d92d7318cb6f2e57e133

**Comment by stchang** [comment]
(Low content comment for now.)

Not sure if it's related, but I'm still getting segfaults after a few minutes of an infinitely expanding macro.

I can reliably reproduce but not with a small example so I will keep working on it.
