### ISSUE TITLE
segfault when building 

### ISSUE THREAD

**Issue by samth** [racket/racket#1928]
I get a consistent segfault when building at

```
racket3m: running: <pkgs>/racket-doc/scribblings/foreign/foreign.scrbl
```

However this is a slightly out-of-date install of some other packages, so I'm going to try `raco pkg update --all` and see if it goes away.

Backtrace:

```
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007ffff711437a in __GI_abort () at abort.c:89
#2  0x0000555555845d20 in fault_handler (sn=<optimized out>, si=<optimized out>, ctx=<optimized out>)
    at ../../../racket/gc2/sighand.c:101
#3  <signal handler called>
#4  0x00005555558333e5 in c_to_scheme (already_ptr=<optimized out>, type=<optimized out>, src=<optimized out>,
    delta=delta@entry=0, gcsrc=gcsrc@entry=1) at ../../../racket/gc2/../src/../../foreign/foreign.c:1771
#5  0x000055555583324c in c_to_scheme (already_ptr=<optimized out>, type=<optimized out>, src=<optimized out>,
    delta=delta@entry=0, gcsrc=gcsrc@entry=1) at ../../../racket/gc2/../src/../../foreign/foreign.c:1737
#6  0x000055555583324c in c_to_scheme (already_ptr=<optimized out>, type=<optimized out>, src=<optimized out>,
    delta=delta@entry=0, gcsrc=gcsrc@entry=1) at ../../../racket/gc2/../src/../../foreign/foreign.c:1737
#7  0x000055555583824f in foreign_ptr_ref (argc=4, argv=<optimized out>)
    at ../../../racket/gc2/../src/../../foreign/foreign.c:3076
#8  0x00007ffff7fe3532 in ?? ()
#9  0x00007fffbb581dd0 in ?? ()
#10 0x00007fff81c01c55 in ?? ()
#11 0x00007fffd7ff8620 in ?? ()
#12 0x0000000000000001 in ?? ()
#13 0x00007fffd7ff8588 in ?? ()
#14 0x00007fffbb581de0 in ?? ()
#15 0x000000000000000b in ?? ()
#16 0x0000000000000021 in ?? ()
#17 0xfffffffffffff250 in ?? ()
#18 0x00007fffbb581de8 in ?? ()
#19 0x00007fffbb581de8 in ?? ()
#20 0x00005555555cbace in scheme_do_eval (obj=<optimized out>, num_rands=1, num_rands@entry=-1, rands=<optimized out>,
    rands@entry=0x0, get_value=get_value@entry=1) at ../../../racket/gc2/../src/eval.c:3062
#21 0x00005555555cd9d2 in scheme_do_eval (obj=<optimized out>, num_rands=<optimized out>, num_rands@entry=0,
    rands=<optimized out>, get_value=get_value@entry=-1) at ../../../racket/gc2/../src/eval.c:3457
#22 0x00005555555f49d1 in scheme_finish_apply_for_prompt (prompt=0x0, _prompt_tag=<optimized out>, proc=<optimized out>,
    argc=argc@entry=0, argv=<optimized out>) at ../../../racket/gc2/../src/fun.c:6651
#23 0x00005555555f4b86 in scheme_apply_for_prompt (prompt=<optimized out>, prompt_tag=<optimized out>, proc=<optimized out>,
    argc=argc@entry=0, argv=<optimized out>) at ../../../racket/gc2/../src/fun.c:6730
#24 0x00005555555f9565 in call_with_prompt (in_argc=<optimized out>, in_argv=<optimized out>)
    at ../../../racket/gc2/../src/fun.c:7229
```

**Comment by mflatt** [comment]
Is "serialize-cstruct-lib" among the packages that are out-of-date in your installation?

**Comment by samth** [comment]
Probably, since the segfault went away after updating.
