### ISSUE TITLE
crash in futures

### ISSUE THREAD

**Issue by samth** [racket/racket#3145]
Reported by @dzoep 

```
#lang racket/gui

(require racket/future racket/fixnum racket/cmdline)

(define width 800)
(define height 600)

(define framebuffer (make-fxvector (* width height)))
(define pixels (make-bytes (* width height 4)))

(define max-depth 0)

(command-line
 #:once-each
 (("-d" "--depth") d "Futures binary partitioning depth" (set! max-depth
(string->number d))))

(file-stream-buffer-mode (current-output-port) 'none)

(parameterize ((current-eventspace (make-eventspace)))
  (define win (new frame%
                   (label "test")
                   (width width)
                   (height height)))
  (define bmp (make-bitmap width height))
  (define canvas (new canvas%
                      (parent win)
                      (paint-callback
                       (λ (c dc)
                         (send dc draw-bitmap bmp 0 0)))
                      ))

  (define (single-run)
    (define (do-bflip start end (depth 0))
      (cond ((fx< depth max-depth)
             (define cnt (fx- end start))
             (define cnt2 (fxrshift cnt 1))
             (define mid (fx+ start cnt2))
             (let ((f (future
                       (λ ()
                         (do-bflip start mid (fx+ depth 1))))))
               (do-bflip mid end (fx+ depth 1))
               (touch f)))
            (else
             (for ((i (in-range start end)))
               (define c (fxvector-ref framebuffer i))
               (bytes-set! pixels (+ (* i 4) 0) #xff)
               (bytes-set! pixels (+ (* i 4) 1) (fxand (fxrshift c 16)
#xff))
               (bytes-set! pixels (+ (* i 4) 2) (fxand (fxrshift c 8) #xff))
               (bytes-set! pixels (+ (* i 4) 3) (fxand c #xff))))))
    (do-bflip 0 (* width height))
    (send canvas refresh-now))
(send win show #t)

  (define appthread
    (thread
     (λ ()
       (let loop ()
         (single-run)
         (loop)))))
  (thread-wait appthread))
```

**Comment by samth** [comment]
```
Thread 1 "futures-bug.rkt" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c65899 in __GI_abort () at abort.c:79
#2  0x00005555557eaea5 in fault_handler (sn=<optimized out>, si=<optimized out>, 
    ctx=<optimized out>) at ../../../racket/gc2/sighand.c:103
#3  <signal handler called>
#4  do_next_finalization (o=0x7ffff5111ce8, _data=0x0)
    at ../../../racket/gc2/../src/salloc.c:1684
#5  0x00005555557ef30b in garbage_collect (gc=gc@entry=0x5555559da360, 
    force_full=force_full@entry=0, no_full=no_full@entry=0, 
    switching_master=switching_master@entry=0, lmi=lmi@entry=0x0)
    at ../../../racket/gc2/newgc.c:5923
#6  0x00005555557f0f72 in collect_now (nomajor=<optimized out>, 
    major=<optimized out>, gc=<optimized out>) at ../../../racket/gc2/newgc.c:875
#7  collect_now (gc=0x5555559da360, major=0, nomajor=0)
    at ../../../racket/gc2/newgc.c:855
#8  0x00005555557f7bac in GC_make_jit_nursery_page (count=<optimized out>, 
    sz=sz@entry=0x7fffffffb338) at ../../../racket/gc2/newgc.c:1887
#9  0x00005555555d512a in do_invoke_rtcall (fs=<optimized out>, 
    future=<optimized out>) at ../../../racket/gc2/../src/future.c:3476
#10 0x00005555555d5797 in invoke_rtcall (fs=<optimized out>, future=<optimized out>, 
    is_atomic=is_atomic@entry=1) at ../../../racket/gc2/../src/future.c:3697
#11 0x00005555555d5fdb in scheme_check_future_work ()
    at ../../../racket/gc2/../src/future.c:2596
#12 0x00005555557c0c23 in scheme_thread_block (sleep_time=sleep_time@entry=0)
    at ../../../racket/gc2/../src/thread.c:4904
#13 0x00005555555a2008 in scheme_do_eval (obj=<optimized out>, 
    num_rands=<optimized out>, num_rands@entry=2, rands=<optimized out>, 
    get_value=get_value@entry=-1) at ../../../racket/gc2/../src/eval.c:2491
#14 0x00005555555a2d92 in _scheme_apply_multi_from_native (rator=<optimized out>, 
    argc=2, argv=<optimized out>) at ../../../racket/gc2/../src/schnapp.inc:100
#15 0x00007ffff7ab8cde in ?? ()
#16 0x0000000000000000 in ?? ()
```

**Comment by mflatt** [comment]
I'm pretty sure that commit fixes this specific crash, but more testing would be appreciated.

**Comment by samth** [comment]
There have long been intermittent crashes on DrDr in futures tests, on Racket BC, so hopefully this will fix those as well.

**Comment by dzoep** [comment]
I am already running the patched version and testing back from the de-optimized example through unsafe-bytes-set! to the fastest unsafe-u16vector-set! with bigger fxvectors as source. I'll stress test it using all the combinations I used in the past and summarize the results. Reading the rationale behind the patch, it now finally makes sense, why the GUI thread was necessary - the futures alone definitely did not trigger any GC actions.

**Comment by samth** [comment]
@mflatt should we try to write a smaller test (probably generating lots of finalizers) that triggers this, or should we add @dzoep's original test?

**Comment by dzoep** [comment]
After a few hours of stress-testing, I can confirm it is not possible to crash the patched version no matter the total load. Between successive GUI calls, I actually perform two tasks with nested futures and for both I tried the maximum depth to be from 1 to 4, which is 2,4,8 and 16 threads, meaning 1,3,7 and 15 futures respectively. All tests were performed on data sets with 300k-3.5M elements and there is no difference (actually the thread scheduling looks similar for all of the workloads too). Just for the record, everything was done on a 4-core 8-HT CPU (i7-8550U).
