### ISSUE TITLE
file dialog functions hang

### ISSUE THREAD

**Issue by yjqww6** [racket/racket#3231]
I'm using RacketCS v7.7.0.7 on Linux.
When I calling file dialog functions(get-file, put-file, get-directory, and get-file-list), it hangs and repeatly prints
```
the expected number of arguments does not match the given number
  expected: 1
  given: 0; original exception raised: exception raised by error escape handler: #<procedure>: arity mismatch;
```
to the console, and sometimes it interleaves
```
invalid memory reference.  Some debugging context lost
```

**Comment by mflatt** [comment]
Thanks for the report!

I have not been able to replicate the problem, so far.  Is the problem specific to CS, or do you also see similar symptoms with the regular distribution? Which variant of Linux do you run?

**Comment by yjqww6** [comment]
@mflatt I'm using ubuntu 16.04, the latest RacketBC snapshot works fine.

Also, calling those functions from command line in RacketCS prints
```
$ racket -l racket/gui -e '(get-file)'
invalid memory reference.  Some debugging context lost
  context...:
   condition->exn
   body of top-level
   dynamic-wind
   eval-one-top
   call-in-empty-metacontinuation-frame
   proc
   call-in-empty-metacontinuation-frame
   thunk_10
   call-in-empty-metacontinuation-frame
   call-with-empty-metacontinuation-frame-for-swap
```

**Comment by yjqww6** [comment]
I have tried RacketCS 7.7 and 20200604-31c5644 on two ubuntu 16.04 machines and I got same problems.

But it works on ubuntu 18.04, with warning printed
```
$ ./racket -l racket/gui -e '(get-file)'
Gtk-Message: 12:48:35.794: GtkDialog mapped without a transient parent. This is discouraged.
#f
```

**Comment by mflatt** [comment]
I still haven't found the right installation to trigger this problem. Can you try running in gdb to get more information?

Specifically, try `gdb racket`, then `run -l racket/gui -e '(get-file)'`, then at the invalid memory reference (which I expect to break back into gdb), `bt` for a backtrace. The result might not tell us anything, but it might provide a hint.

**Comment by yjqww6** [comment]
Unfortunately, it seems the output dosen't have anything interesting.
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeb790700 (LWP 17425)]
[New Thread 0x7fffeaf8f700 (LWP 17427)]
[New Thread 0x7fffea78e700 (LWP 17428)]
[New Thread 0x7fffda231700 (LWP 17429)]

Thread 1 "racket" received signal SIGSEGV, Segmentation fault.
0x0000000000412f35 in ?? ()
(gdb) bt
#0  0x0000000000412f35 in ?? ()
#1  0x0000000041d04112 in ?? ()
#2  0x0000000000000005 in ?? ()
#3  0x0000000041d04040 in ?? ()
#4  0x0000000000000000 in ?? ()
(gdb) quit
```

Also, I found it get into trouble only when calling without a parent.


I don't know whether it is machine-related, but the simplest way for me to reproduce the problem is 
1. download http://old-releases.ubuntu.com/releases/16.04.3/ubuntu-16.04.3-desktop-amd64.iso
2. open it in virtualbox, "Try Ubuntu"(no need to install)
3. wget racketcs v7.7 and install
4. run the command above for get-file

**Comment by mflatt** [comment]
Thanks for the detailed steps! But I'd expect to see that crash (and do) with v7.7, since there was a problem with logging. I should have been more clear before that v7.7.07 has some relevant bug fixes.

When I follow your steps but substitute v7.7.0.7, I don't get a crash. But if I understand correctly, you are seeing crashes also with v7.7.0.7, at least with some configurations.

**Comment by yjqww6** [comment]
20200608-7abdaee snapshot is ok to reproduce, but I cannot reproduce it since 20200609-c2cae5b.
I'm not clear whether it's fixed or hidden. Are there any commits potentially related?
